# Ce dossier est utilisé pour afficher ce projet sur mon site web (https://smartineau.me)
# This folder is used to display this project on my website (https://smartineau.me)
description = "Une extension VSCode qui permet d'utiliser Degit directement dans VSCode"
etiquettes = [ "ts", "vscode" ]
url_site_web = "https://marketplace.visualstudio.com/items?itemName=samumartineau.degit-templates"
contenu = "./article.md"
date_de_creation = 2020-06-21T15:23:25.476Z
